export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_FULFILLED = 'FETCH_NOTIFICATIONS_FULFILLED';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS_FULFILLED = 'UPDATE_NOTIFICATIONS_FULFILLED';

export const BOOTCAMPS_FETCH = 'BOOTCAMPS_FETCH';
export const BOOTCAMPS_FETCH_FULFILLED = 'BOOTCAMPS_FETCH_FULFILLED';

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_WITH_NOTE = 'LOGOUT_WITH_NOTE';