export const REGISTER_BOOTCAMPS_FETCH = 'BOOTCAMPS_FETCH';
export const REGISTER_BOOTCAMPS_FETCH_FULFILLED = 'BOOTCAMPS_FETCH_FULFILLED';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_REGISTRATION_INFO = 'SET_REGISTRATION_INFO';

export const SUBMIT_COUPON = 'SUBMIT_COUPON';
export const SUBMIT_COUPON_FULFILLED = 'SUBMIT_COUPON_FULFILLED';

export const SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION';
export const SUBMIT_REGISTRATION_FULFILLED = 'SUBMIT_REGISTRATION_FULFILLED';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_FULFILLED = 'GET_TOKEN_FULFILLED';